name: ayurveda
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.2+4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.0
  launcher_name: ^1.0.2
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  package_rename: ^1.7.0

launcher_name:
  default: "Aayurveda" 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

package_rename_config:
  android:
    app_name: "Aayurveda"
    package_name: "ayurveda.stime.in"
    override_old_package:
    lang: 

  ios:
    app_name: "Aayurveda"
    bundle_name: "Aayurveda"
    package_name: "aayurveda.stime.in"

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets: 
    - assets/images/

  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Light.ttf
        weight: 300
      - asset: assets/fonts/OpenSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/OpenSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/OpenSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/OpenSans-ExtraBold.ttf
        weight: 800
